title: Tuncay Kayaoglu
email: "https://tunc-ay.github.io"
description: >-
  Personal website for Tuncay Kayaoglu
baseurl: ""
url: "https://tunc-ay.github.io"
twitter_username: tunkay
github_username:  tunc-ay

theme: minima