# Site settings
title: Tuncay Kayaoglu
email: tuncaykayaoglu@yahoo.com
description: >-
  Technical writer specializing in software documentation, API documentation,
  and user guides. Experienced in creating clear, concise, and user-friendly documentation.
baseurl: ""
url: "https://tunc-ay.github.io"

# Social links
twitter_username: tunkay
github_username: tunc-ay
linkedin_username: tuncaykayaoglu

# Navigation
include:
  - _pages

# Navigation links
header_pages:
  - about.md
  - projects.md
  - blog.md

# Build settings
markdown: kramdown
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tuncay Kayaoglu"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME
  - .gitignore
  - .sass-cache/

# SEO settings
lang: en
author: Tuncay Kayaoglu

# Optional: Add these for better SEO
twitter:
  username: tunkay
  card: summary
social:
  name: Tuncay Kayaoglu
  links:
    - https://twitter.com/tunkay
    - https://www.linkedin.com/in/tuncaykayaoglu
    - https://github.com/tunc-ay