name: Run Selenium on Website Update

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 requests

      - name: Run Selenium Script
        run: |
          python screenshots.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Screenshots
        run: |
          git add screenshots/
          git commit -m "Add new screenshots"
          git push origin main